name = "SafePETSc"
uuid = "50acdc01-ce88-4ca7-bd87-6916c254362e"
authors = ["SÃ©bastien Loisel <S.Loisel@hw.ac.uk>"]
version = "0.1.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
PETSc = "ace2c81b-2b5f-4b1e-a30d-d662738edfe0"
SCALAPACK32_jll = "aabda75e-bfe4-5a37-92e3-ffe54af3c273"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.11"
LinearAlgebra = "1.11.0"
MPI = "0.20"
OpenBLAS32_jll = "0.3.29"
PETSc = "0.3.1"
SCALAPACK32_jll = "2.2.2"
SHA = "0.7.0"
Serialization = "1.11.0"
SparseArrays = "1.11.0"

[extras]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
