name = "SafePETSc"
uuid = "50acdc01-ce88-4ca7-bd87-6916c254362e"
authors = ["SÃ©bastien Loisel <S.Loisel@hw.ac.uk>"]
version = "0.1.17"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PETSc = "ace2c81b-2b5f-4b1e-a30d-d662738edfe0"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
MPI = "0.20"
PETSc = "0.3.1"
julia = "1.10"

[extras]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
